In [1]:
a = 10
b = 20
print(a + b)

30


In [1]:
u = [2, 2]
v = [1, 2]
z = [-3, 5]

In [2]:
result = []

In [ ]:
for i in range(len(u)):
    result.append(u[i] + v[i] + z[i])

In [14]:
print(result)

[0, 9, 0, 9]


In [15]:
result = [sum(t) for t in zip(u, v, z)]
print(result)

[0, 9]


In [16]:
def vector_addition(*args):
    return [sum(t) for t in zip(*args)]
u = [2,2]
v = [1,2]
z = [-3,5]
print(vector_addition(u,v,z))

[0, 9]


In [17]:
vectors = [[2,2], [1,2], [-3,5]]
print(vector_addition(*vectors))

[0, 9]


In [18]:
import numpy as np

In [21]:
nu = np.array([2,2])
nv = np.array([1,2])
nz = np.array([-3,5])

In [22]:
sum = nu + nv + nz
print(sum)

[0 9]


In [23]:
u = [1, 2, 3]
v = [4, 3, 3]
alpha = 2

In [25]:
del sum

In [26]:
result = [alpha * sum(t) for t in zip(u,v)]
print(result)    

[10, 10, 12]


In [30]:
nu = np.array([1,2,3])
nv = np.array([4,3,3])
sum = alpha * (nu + nv) # scalar인 2를 numpy가 알아서 [2, 2, 2]로 broadcasting 시켜줘서 식 성립 가능
print(sum)

[10 10 12]


In [32]:
del sum

In [33]:
matrix_a = [[3,6], [4,5]]
matrix_b = [[5,8], [6,7]]
result = [[sum(row) for row in zip(*t)] for t in zip(matrix_a, matrix_b)]
print(result) # matrix a와 b에서 한쌍씩 데이터 추출 -> 그 추출된 데이터도 한 쌍으로 이루어짐 -> 그 데이터를 다시 각각으로 추출(zip)해서 합

[[8, 14], [10, 12]]


In [34]:
nmatrix_a = np.array([[3,6], [4,5]])
nmatrix_b = np.array([[5,8], [6,7]])

result = nmatrix_a + nmatrix_b
print(result)

[[ 8 14]
 [10 12]]


In [54]:
aMat = [[1, 2, 3], [4, 5, 6]]
# a_t = [[1, 4], [2, 5], [3, 6]]

In [55]:
result = [matrix for matrix in zip(aMat[0], a[1])]
print(result)
print(type(result))
print(type(a))
bomb1 = [1, 2 ,3]
bomb2 = (1, 2, 3)
print(type(bomb1), type(bomb2))

[(1, 4), (2, 5), (3, 6)]
<class 'list'>
<class 'list'>
<class 'list'> <class 'tuple'>


In [69]:
result =[[t for t in i] for i in zip(aMat[0], aMat[1])]
print(result)
print(type(result))

[[1, 4], [2, 5], [3, 6]]
<class 'list'>


In [84]:
result =[[t for t in i] for i in zip(*aMat)]
print(result)
print(type(result))

result_1 = [aMat[f] for f in range(len(aMat))]
print(result_1)

[[1, 4], [2, 5], [3, 6]]
<class 'list'>
[[1, 2, 3], [4, 5, 6]]


In [85]:
print(*aMat) # 묶여있는 요소들을 풀어주는 Asterisk => *(1,2,3,4) => 1 2 3 4

[1, 2, 3] [4, 5, 6]


In [86]:
matrix_a = np.array([[1,2,3],[4,5,6]])
matrix_a_t = matrix_a.T
matrix_a_t2 = np.transpose(matrix_a)
print(matrix_a_t)
print(matrix_a_t2)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
